"""
Generate QA pairs in two modes, supporting both API and local LLM backends:
- normalized: A from normalized_data.json (block text), chunk_id from all_chunks.json (chunk
  that contains A); Q generated by LLM given passage (chunk text) + answer. Optional --no-llm-q
  uses rule-based Q templates instead.
- llm: one QA per chunk from all_chunks.json using LLM (original behavior).

Backends:
- api: use OpenAI-compatible HTTP API (ModelScope endpoint by default, see config.yaml llm.api).
- local: use a local transformers model (see config.yaml llm.local).

Output: data/answers/qa_from_normalized.jsonl (normalized) or data/answers/qa_pairs.jsonl (llm).
"""
import argparse
import csv
import json
import logging
import os
import re
from pathlib import Path
from typing import Optional

import torch
from dotenv import load_dotenv
from modelscope import AutoModelForCausalLM, AutoTokenizer
from openai import OpenAI
from tqdm import tqdm

from src.utils import load_config

load_dotenv()

CONFIG = load_config()
PATHS = CONFIG.get("paths", {})
ALL_CHUNK_PATH = PATHS.get("all_chunk_path", "results/chunk_results/all_chunks.json")
NORMALIZED_DATA_PATH = PATHS.get("normalized_data_path", "data/answers/normalized_data.json")
QA_OUTPUT_PATH = "data/answers/qa_pairs.jsonl"
QA_NORMALIZED_OUTPUT_PATH = "data/answers/qa_from_normalized.jsonl"
GOLD_ANSWERS_CSV_PATH = PATHS.get("gold_answers_csv", "data/answers/gold_answers.csv")
LLM_CONFIG = CONFIG.get("llm", {})
API_LLM_CONFIG = LLM_CONFIG.get("api", {})
LOCAL_LLM_CONFIG = LLM_CONFIG.get("local", {})
DEFAULT_BACKEND = LLM_CONFIG.get("mode", "api")
API_MODEL_ID = API_LLM_CONFIG.get("model", "Qwen/Qwen3-8B")
LOCAL_MODEL_NAME = LOCAL_LLM_CONFIG.get("model_name", "Qwen/Qwen3-4B-Instruct-2507")

# Block types used to generate QA; answer = block text from normalized_data.
QA_BLOCK_TYPES = ("title", "text_block", "figure_caption", "table_caption")
# Rule-based question templates (used only when --no-llm-q).
QUESTION_TEMPLATES = {
    "title": "本页标题是什么？",
    "text_block": "本段内容是什么？",
    "figure_caption": "该图/表的说明文字是什么？",
    "table_caption": "该表格的标题是什么？",
}

# Prompt: generate one question such that the given answer is the answer (for normalized mode).
QA_QUESTION_PROMPT = """你现在要为一个问答数据集生成中文问题。

给定一段上下文（passage）以及一个确切的答案字符串（answer，且是上下文中的子串），请写出【一个】自然的中文问题，使得该问题的答案正好是给定的 answer。

要求：
- 问句必须是完整的中文句子，并以问号（？或?）结尾。
- 问句要足够具体，使得在这段上下文中只有给定的 answer 是合理答案。
- 不要输出 \"...\"，也不要输出占位符或纯标点。
- 问句长度最好不少于 8 个汉字。
- 不要在问题里直接完整复述 answer 的内容。
- 最终只输出一个 JSON 对象，键名为 question，值为你生成的问题内容。不要输出任何解释性文字。

下面是上下文 passage：
---
{passage}
---

下面是该问题对应的答案 answer：
---
{answer}
---"""

QA_PROMPT = """Based on the following passage, generate exactly one question-answer pair.
Requirements:
- The answer MUST be a continuous substring of the passage (copy from the passage).
- Output valid JSON only, no other text: {"question": "...", "answer": "..."}

Passage:
---
{text}
---"""

logger = logging.getLogger(__name__)

_LOCAL_TOKENIZER: Optional[AutoTokenizer] = None
_LOCAL_MODEL: Optional[AutoModelForCausalLM] = None


def _ensure_local_model_loaded() -> tuple[AutoTokenizer, AutoModelForCausalLM]:
    """Lazily load local transformers model for text generation."""
    global _LOCAL_TOKENIZER, _LOCAL_MODEL
    if _LOCAL_MODEL is not None and _LOCAL_TOKENIZER is not None:
        return _LOCAL_TOKENIZER, _LOCAL_MODEL

    model_name = LOCAL_MODEL_NAME
    torch_dtype_cfg = LOCAL_LLM_CONFIG.get("torch_dtype", "auto")
    if torch_dtype_cfg == "float16":
        torch_dtype = torch.float16
    elif torch_dtype_cfg == "bfloat16":
        torch_dtype = torch.bfloat16
    else:
        torch_dtype = "auto"

    logger.info("Loading local LLM model: %s", model_name)
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch_dtype,
        device_map="auto",
        trust_remote_code=True,
    )
    _LOCAL_TOKENIZER = tokenizer
    _LOCAL_MODEL = model
    return tokenizer, model


def unload_local_model() -> None:
    """Release the local LLM and tokenizer from GPU memory. Call after gold QA generation to free VRAM for later stages (e.g. reranker)."""
    global _LOCAL_TOKENIZER, _LOCAL_MODEL
    if _LOCAL_MODEL is not None:
        del _LOCAL_MODEL
        _LOCAL_MODEL = None
    if _LOCAL_TOKENIZER is not None:
        del _LOCAL_TOKENIZER
        _LOCAL_TOKENIZER = None
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    logger.info("Unloaded local LLM and freed GPU cache.")


def _generate_with_backend(prompt: str, backend: str, api_client: Optional[OpenAI]) -> str:
    """Generate completion using either API or local backend."""
    prompt = prompt or ""
    if not prompt.strip():
        return ""

    if backend == "api":
        if api_client is None:
            raise ValueError("API backend selected but api_client is None")
        response = api_client.chat.completions.create(
            model=API_MODEL_ID,
            messages=[{"role": "user", "content": prompt}],
            stream=False,
            extra_body={"enable_thinking": False},
        )
        return (response.choices[0].message.content or "").strip()

    tokenizer, model = _ensure_local_model_loaded()
    # Use chat template for Qwen chat models; disable thinking mode.
    messages = [{"role": "user", "content": prompt}]
    chat_text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=False,
    )
    inputs = tokenizer([chat_text], return_tensors="pt").to(model.device)
    max_new_tokens = int(LOCAL_LLM_CONFIG.get("max_tokens", 256))
    temperature = float(LOCAL_LLM_CONFIG.get("temperature", 0.7))
    do_sample = bool(LOCAL_LLM_CONFIG.get("do_sample", True))
    top_p = float(LOCAL_LLM_CONFIG.get("top_p", 0.8))
    top_k = int(LOCAL_LLM_CONFIG.get("top_k", 20))
    min_p = float(LOCAL_LLM_CONFIG.get("min_p", 0.0))
    output_ids = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=do_sample,
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
        min_p=min_p,
    )
    full_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    if full_text.startswith(prompt):
        return full_text[len(prompt) :].strip()
    return full_text.strip()


def load_chunks(path: str) -> list[dict]:
    """Load all_chunks.json. Returns list of chunk dicts."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, list) else []


def load_normalized(path: str) -> list[dict]:
    """Load normalized_data.json. Returns list of page items (page_dets, relation, page_no, image_path)."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, list) else []


def image_path_to_file_name(image_path: str) -> str:
    """Derive file_name for chunk lookup from OmniDocBench image_path (e.g. xxx.pdf_11.jpg -> xxx.pdf_11)."""
    if not image_path:
        return ""
    return Path(image_path).stem


def build_page_chunk_index(chunks: list[dict]) -> dict[tuple[str, int], list[dict]]:
    """Build index (file_name, page_index) -> list of chunks for that page."""
    index = {}
    for chunk in chunks:
        key = (chunk.get("file_name", ""), int(chunk.get("page_index", 0)))
        index.setdefault(key, []).append(chunk)
    return index


def collect_qa_candidates(normalized_data: list[dict]) -> list[tuple[str, str, int, str]]:
    """
    From normalized_data produce (answer, file_name, page_index, category_type) per content block.
    Answer is the block text; Q is not produced here (LLM or template later).
    """
    candidates = []
    for page_item in normalized_data:
        page_dets = page_item.get("page_dets", [])
        page_no = page_item.get("page_no", 0)
        image_path = page_item.get("image_path", "")
        file_name = image_path_to_file_name(image_path)
        if not file_name:
            continue
        for det in page_dets:
            category_type = det.get("category_type", "")
            text = (det.get("text") or "").strip()
            if category_type not in QA_BLOCK_TYPES or not text:
                continue
            candidates.append((text, file_name, page_no, category_type))
    return candidates


def _normalize_whitespace(s: str) -> str:
    return " ".join(s.split())


def find_chunk_for_answer(
    page_chunk_index: dict[tuple[str, int], list[dict]],
    file_name: str,
    page_index: int,
    answer: str,
) -> dict | None:
    """Find a chunk on (file_name, page_index) whose text contains answer (exact or normalized)."""
    key = (file_name, page_index)
    chunks = page_chunk_index.get(key, [])
    if not chunks:
        return None
    for chunk in chunks:
        text = chunk.get("text", "")
        if answer in text:
            return chunk
    answer_norm = _normalize_whitespace(answer)
    for chunk in chunks:
        if answer_norm in _normalize_whitespace(chunk.get("text", "")):
            return chunk
    if len(answer) > 50:
        for chunk in chunks:
            if answer[:50] in chunk.get("text", ""):
                return chunk
    return None


def call_llm_question(
    passage: str,
    answer: str,
    backend: str,
    api_client: Optional[OpenAI],
) -> str:
    """Generate one question such that the answer is the given answer (answer must be in passage)."""
    passage = (passage or "").strip()[:4000]
    answer = (answer or "").strip()
    if not passage or not answer:
        return ""
    prompt = QA_QUESTION_PROMPT.format(passage=passage, answer=answer)
    return _generate_with_backend(prompt, backend=backend, api_client=api_client)


def parse_question(raw: str) -> str:
    """Parse JSON {\"question\": \"...\"} from LLM output."""
    raw = raw.strip()
    if "```" in raw:
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
    start = raw.find("{")
    end = raw.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            obj = json.loads(raw[start : end + 1])
            return (obj.get("question") or "").strip()
        except json.JSONDecodeError:
            pass
    m = re.search(r'"question"\s*:\s*"([^"]*)"', raw)
    return (m.group(1) if m else "").strip()


def run_normalized_mode(
    normalized_path: str,
    chunks_path: str,
    output_path: str,
    use_llm_question: bool = True,
    backend: str = "api",
    api_client: Optional[OpenAI] = None,
) -> None:
    """
    Generate QA: A from normalized_data (block text), chunk_id from all_chunks;
    Q from LLM (passage + answer) if use_llm_question else from rule template.
    """
    normalized_data = load_normalized(normalized_path)
    if not normalized_data:
        logger.warning("No normalized data at %s", normalized_path)
        return
    chunks = load_chunks(chunks_path)
    if not chunks:
        logger.warning("No chunks at %s", chunks_path)
        return
    if use_llm_question and backend == "api" and api_client is None:
        raise ValueError("use_llm_question=True with api backend requires api_client (set API key or use --backend local)")
    index = build_page_chunk_index(chunks)
    candidates = collect_qa_candidates(normalized_data)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    qid = 0
    skipped = 0
    gold_rows: list[dict] = []
    with open(output_path, "w", encoding="utf-8") as out:
        for answer, file_name, page_index, category_type in tqdm(
            candidates, desc="QA (link chunk + gen Q)" if use_llm_question else "Linking QA to chunks"
        ):
            chunk = find_chunk_for_answer(index, file_name, page_index, answer)
            if chunk is None:
                skipped += 1
                continue
            if use_llm_question:
                raw_q = call_llm_question(
                    chunk.get("text", ""),
                    answer,
                    backend=backend,
                    api_client=api_client,
                )
                question = parse_question(raw_q)
                if not question:
                    skipped += 1
                    continue
            else:
                question = QUESTION_TEMPLATES.get(category_type, "本段内容是什么？")
            qid += 1
            record = {
                "qid": f"nd_{qid}",
                "question": question,
                "answer": answer,
                "chunk_id": chunk.get("chunk_id", ""),
                "file_name": chunk.get("file_name", ""),
                "page_index": chunk.get("page_index", 0),
            }
            out.write(json.dumps(record, ensure_ascii=False) + "\n")
            gold_rows.append(
                {
                    "question": question,
                    "gold_answer": answer,
                    "gold_chunk_ids": record["chunk_id"],
                    "num_gold_chunks": 1,
                    "doc_file_name": record["file_name"],
                }
            )

    # Also write gold_answers.csv for evaluator / pipeline usage.
    if gold_rows:
        os.makedirs(os.path.dirname(GOLD_ANSWERS_CSV_PATH) or ".", exist_ok=True)
        fieldnames = ["question", "gold_answer", "gold_chunk_ids", "num_gold_chunks", "doc_file_name"]
        with open(GOLD_ANSWERS_CSV_PATH, "w", encoding="utf-8", newline="") as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(gold_rows)
        logger.info(
            "Wrote %d gold answers to %s",
            len(gold_rows),
            GOLD_ANSWERS_CSV_PATH,
        )

    logger.info("Wrote %d QA pairs to %s (skipped %d)", qid, output_path, skipped)


def call_llm(text: str, backend: str, api_client: Optional[OpenAI]) -> str:
    """Generate one QA JSON string for a chunk of text (llm mode)."""
    if not text or not text.strip():
        return ""
    prompt = QA_PROMPT.format(text=text.strip()[:4000])
    return _generate_with_backend(prompt, backend=backend, api_client=api_client)


def parse_qa(raw: str) -> tuple[str, str]:
    """Parse JSON or fallback to simple extraction. Returns (question, answer)."""
    raw = raw.strip()
    if "```" in raw:
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
    start = raw.find("{")
    end = raw.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            obj = json.loads(raw[start : end + 1])
            return (obj.get("question", ""), obj.get("answer", ""))
        except json.JSONDecodeError:
            pass
    q = re.search(r'"question"\s*:\s*"([^"]*)"', raw)
    a = re.search(r'"answer"\s*:\s*"([^"]*)"', raw)
    return (q.group(1) if q else "", a.group(1) if a else "")


def run_llm_mode(
    chunks_path: str,
    output_path: str,
    backend: str = "api",
    api_client: Optional[OpenAI] = None,
) -> None:
    """Generate one QA per chunk using LLM (original behavior)."""
    if backend == "api" and api_client is None:
        raise ValueError("API backend selected for llm mode but api_client is None")
    chunks = load_chunks(chunks_path)
    if not chunks:
        logger.warning("No chunks found at %s", chunks_path)
        return
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    qid = 0
    with open(output_path, "w", encoding="utf-8") as out:
        for chunk in tqdm(chunks, desc="Generating QA"):
            text = chunk.get("text", "")
            if not text or not text.strip():
                continue
            raw = call_llm(text, backend=backend, api_client=api_client)
            question, answer = parse_qa(raw)
            if not question or not answer:
                continue
            qid += 1
            record = {
                "qid": f"qa_{qid}",
                "question": question,
                "answer": answer,
                "chunk_id": chunk.get("chunk_id", ""),
                "file_name": chunk.get("file_name", ""),
                "page_index": chunk.get("page_index", 0),
            }
            out.write(json.dumps(record, ensure_ascii=False) + "\n")
    logger.info("Wrote %d QA pairs to %s", qid, output_path)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s %(message)s")
    parser = argparse.ArgumentParser(description="Generate QA from chunks (normalized or LLM).")
    parser.add_argument(
        "--mode",
        choices=("normalized", "llm"),
        default="normalized",
        help="normalized: A from normalized_data + chunk from all_chunks, Q by LLM; llm: one QA per chunk via LLM",
    )
    parser.add_argument(
        "--backend",
        choices=("api", "local"),
        default=DEFAULT_BACKEND,
        help="LLM backend: api (OpenAI-compatible HTTP API) or local (transformers)",
    )
    parser.add_argument(
        "--no-llm-q",
        action="store_true",
        help="[normalized only] use rule-based question templates instead of LLM for Q",
    )
    parser.add_argument("--normalized-path", default=NORMALIZED_DATA_PATH, help="Path to normalized_data.json")
    parser.add_argument("--chunks-path", default=ALL_CHUNK_PATH, help="Path to all_chunks.json")
    parser.add_argument("--output", help="Output jsonl path (default: qa_from_normalized.jsonl or qa_pairs.jsonl)")
    args = parser.parse_args()

    backend = args.backend

    if args.mode == "normalized":
        output_path = args.output or QA_NORMALIZED_OUTPUT_PATH
        use_llm_q = not args.no_llm_q
        api_client: Optional[OpenAI] = None
        if use_llm_q and backend == "api":
            api_key = os.getenv("QWEN_API_KEY") or os.getenv("OPENAI_API_KEY")
            if not api_key:
                raise ValueError("Set QWEN_API_KEY or OPENAI_API_KEY in .env for API backend, or use --backend local")
            api_client = OpenAI(
                base_url="https://api-inference.modelscope.cn/v1",
                api_key=api_key,
            )
        run_normalized_mode(
            args.normalized_path,
            args.chunks_path,
            output_path,
            use_llm_question=use_llm_q,
            backend=backend,
            api_client=api_client,
        )
    else:
        output_path = args.output or QA_OUTPUT_PATH
        api_client: Optional[OpenAI] = None
        if backend == "api":
            api_key = os.getenv("QWEN_API_KEY") or os.getenv("OPENAI_API_KEY")
            if not api_key:
                raise ValueError("Set QWEN_API_KEY or OPENAI_API_KEY in .env for API backend, or use --backend local")
            api_client = OpenAI(
                base_url="https://api-inference.modelscope.cn/v1",
                api_key=api_key,
            )
        run_llm_mode(args.chunks_path, output_path, backend=backend, api_client=api_client)


if __name__ == "__main__":
    main()
